# https://taskfile.dev

version: '3'

vars:
  BINARY: ./tmp/main
  CMD: ./cmd/main.go

tasks:
  default:
    cmds:
      - echo "Try dey guide!"
    silent: true
  test:
    cmds:
        - echo "Running tests..."
        - go test -v ./...
  run:
    cmds:
        - echo "Running the application"
        - go run {{.CMD}}
  run-air:
    cmds:
        - echo "Running the application with air"
        - air
  clean:
    cmds:
        - echo "Cleaning up..."
        - rm -f {{.BINARY}}
  create-tmp:
    cmds:
        - mkdir -p ./tmp
  fmt:
    cmds:
        - echo "Formatting code..."
        - go fmt ./...
  migration:
    cmds:
        - migrate create -ext sql -dir internal/migrate/migrations $(filter-out $@,$(MAKECMDGOALS))

